//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIU_AlumniApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnis
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Dept { get; set; }
        public string Batch { get; set; }
        public string WP { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string FbId { get; set; }
    }
}
